build:
	g++ -Werror -Wall -Wextra -o load load.cpp
	g++ -Werror -Wall -Wextra -o clear clear.cpp
	g++ -Werror -Wall -Wextra -o converter converter.cpp

convert:
	g++ -Werror -Wall -Wextra -o converter converter.cpp

load:
	g++ -Werror -Wall -Wextra -o load load.cpp

clear:
	g++ -Werror -Wall -Wextra -o clear clear.cpp

clean:
	del load.exe
	del clear.exe
	del converter.exe